// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheSqlODataMcp.Persistence.CatalogStore;

#nullable disable

namespace TheSqlODataMcp.Persistence.CatalogStore.Migrations
{
    [DbContext(typeof(ControlStoreDbContext))]
    partial class ControlStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TheSqlODataMcp.Persistence.CatalogStore.StoredCatalogRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MergedCatalogJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MergedHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicalCatalogJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicalHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationResultJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CatalogRevisions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
